#!/bin/sh

# Set permissions on kohana folders
# chmod 777 application/logs application/cache

# escape code to bold and green, reset to black
echo '\033[1;32mInstalling Node Packages\033[0m\n'

# Install nope packages.
sudo npm install

exit 0