#!/bin/sh

# Set permissions on kohana folders
# chmod 777 application/logs application/cache

# escape code to bold and green, reset to black
echo '\033[1;32mInstalling Node Packages\033[0m\n'
echo '(This will take a minute)'

# Install nope packages.
sudo npm install --save-dev

exit 0
